//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatanUP01.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Addresses()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public int AddressId { get; set; }
        public string FullAddress { get; set; }
        public Nullable<int> Floors { get; set; }
        public Nullable<int> Apartments { get; set; }
        public Nullable<int> BuildingYear { get; set; }
        public Nullable<decimal> TotalArea { get; set; }
        public Nullable<System.DateTime> StartManagementDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
