//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatanUP01.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debts
    {
        public int DebtId { get; set; }
        public string Address { get; set; }
        public int ApartmentNumber { get; set; }
        public string OwnerName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<decimal> WaterDebt { get; set; }
        public Nullable<decimal> ElectricityDebt { get; set; }
    }
}
