//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatanUP01.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentId { get; set; }
        public string OwnerName { get; set; }
        public string Address { get; set; }
        public int ApartmentNumber { get; set; }
        public string Period { get; set; }
        public decimal ChargedAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    }
}
