//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatanUP01.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int RequestId { get; set; }
        public int AddressId { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantPhone { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
